// ==UserScript==
// @name         Memrise - autofill
// @namespace    http://tampermonkey.net/
// @version      1.3.3
// @description  Skrypt automatycznie wypęłniający odpowiedzi na Memrisie
// @author       PioLeg
// @match        https://app.memrise.com/aprender/review?course_id=*
// @match        https://app.memrise.com/aprender/learn?course_id=*
// @icon         https://www.google.com/s2/favicons?domain=memrise.com
// @downloadURL  https://github.com/pioleg/memrise-autofill/raw/main/memrise%20-%20autofill.user.js
// @updateURL    https://github.com/pioleg/memrise-autofill/raw/main/memrise%20-%20autofill.user.js
// @grant        none
// @require      http://code.jquery.com/jquery-latest.js
// ==/UserScript==

//-- Remove Tampermonkey warnings about jQuery
let $ = window.$;
function addJQuery(callback) {
    var script = document.createElement("script");
    script.setAttribute("src", "//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js");
    script.addEventListener('load', function() {
        var script = document.createElement("script");
        script.textContent = "window.jQ=jQuery.noConflict(true);(" + callback.toString() + ")();";
        document.body.appendChild(script);
    }, false);
    document.body.appendChild(script);
}

var check = function() {
    $('.sc-dlnjwi.cmdNXR.sc-1r45oz1-0.boVotz.r1ec2z-3.gVLwcN button').click()
}

$(document).ready(function() {
    $(document).bind('keydown',function(e){
       if(e.shiftKey) {
           location.reload();
       }
       if(e.keyCode == 8) {
           var instruction = $("[data-testid=instruction]").text();
           var test = $("[data-testid=testLearnableCard]");
           var word = $(".sc-9f618z-2.gaPucC").text().replace(/ +(?= )/g,'');
           var urlParams = new URLSearchParams(window.location.search);
           var course_id = urlParams.get('course_id');
           var id;
           console.log({instruction});
           console.log({word});
           console.log({course_id});
           for (let i = 0; table.length > i; i++) {
               console.log(table[i][0][0]);
               if (table[i][0][0] == course_id) {
                   id = i;
                   break
               }
           }
           console.log({id});
           if(instruction=="Type the correct translation" || instruction=="Wpisz poprawne tłumaczenie") {
               for (let i = 1; table[id].length > i; i++) {
                   console.log(table[id][i][0]);
                   if (table[id][i][1] == word) {
                       $("input").val($("input").val()+table[id][i][0]+' ');
                       break
                   }
               }
               setTimeout(check, 10);
           }
           //if(instruction=="Choose the correct translation") {
           if(instruction=="Pick the correct answer" || instruction=="Wybierz poprawną odpowiedź") {
               for (let i = 1; table[id].length > i; i++) {
                   console.log(table[id][i][0]);
                   var answer;
                   if (table[id][i][1] == word) {
                       answer = table[id][i][0];
                       break
                   }
                   if (table[id][i][0] == word) {
                       answer = table[id][i][1];
                       break
                   }
               }
               $('button div').each(function(index, value){
                   if($(this).text().replace(/ +(?= )/g,'') == answer) {
                       this.click();
                       setTimeout(check, 10);
                   }
               });
           }

           // TODO
           // Choose the translation for what you hear - Wybierz tłumaczenie tego, co słyszysz
           // Choose the answer you hear - Wybierz odpowiedź, którą słyszysz
           // Pick the correct answer - Wybierz poprawną odpowiedź

       }
    });
});

var table = [
	[
		["1378509"], //English for Maths (audio)
		["Aα","alpha"],
		["Bβ","beta"],
		["Γγ","gamma"],
		["Δδ","delta"],
		["Eε","epsilon"],
		["Ζζ","zeta"],
		["Ηη","eta"],
		["Θθ","theta"],
		["Ιι","iota"],
		["Κκ","kappa"],
		["Λλ","lambda"],
		["Μμ","mu"],
		["Νν","nu"],
		["Ξξ","xi"],
		["Oo","omicron"],
		["Ππ","pi"],
		["Ρρ","rho"],
		["Σσ","sigma"],
		["Ττ","tau"],
		["Υυ","upsilon"],
		["Φφ","phi"],
		["Xχ","chi"],
		["Ψψ","psi"],
		["Ωω","omega"]
	],
	[
		["1488016"], //English for Networking and IT Security
		["Computer network","A group of computers linked together for data sharing"],
		["P2P","The model of communication between equally priviledged nodes"],
		["LAN","A computer network that connects devices within a small area"],
		["pLAN","A computer network that connects devices within a personal area (e.g. Bluetooth)"],
		["WAN","A computer network that extends over a large geographical distance"],
		["CAN","A computer network that connects devices within a university campus"],
		["MAN","A computer network that covers the area of a city"],
		["DHCP","The protocol responsible for assigning basic network configuration (IP addresses etc.)"],
		["DNS","The protocol that translates names into IP adresses"],
		["ARP","The protocol that converts IP addresses into MAC addresses"],
		["MAC","A network card's physical address which is represented by a 48-bit integer"],
		["RARP","The protocol that converts MAC address into IP address"],
		["OSI","The model that describes network communication layers and links between them"],
		["IP address","The logical identifier for a computer or device on a TCP/IP network"],
		["ICMP","The protocol responsible for monitoring the state of the network and forwarding errors within it"],
		["Ping","The network utility providing information about reachability of a specified host"],
		["TCP","The transport protocol that ensures the reliable, error-free delivery of packages"],
		["POP3","The third version of the protocol (RFC 1939) usually used by local e-mail clients to retrieve e-mails from a remote server"],
		["UDP","The transport protocol that does not guarantee the data correctness"],
		["FTP (protocol)","The protocol used for the transfer of files between the server and the client"],
		["SMTP","The Internet standard usually used for sending electronic mail (email)"],
		["NTP","The protocol used for time synchronization within computer networks"],
		["HTTP","The protocol used to transfer data from web server"],
		["revDNS","The part of DNS system responsible for translating IP addresses into domain names"],
		["SMB","The protocol used for resource sharing (eg. printers and files)"],
		["CIFS","The another name of SMB protocol"],
		["BitTorrent","The communications protocol which is used for sharing files in P2P"],
		["Telnet","The standard for the protocol responsible for the control of the remote terminal (sending commands etc.)"],
		["SSH","The cryptographic network protocol which allows you to connect to a remote computer system"],
		["CSMA/CA","The protocol used in the Ethernet for tracking the transfer medium state and avoiding collisions"],
		["CSMA/CD","The protocol used in the Ethernet for tracking the transfer medium state and detecting collisions"],
		["IPv4","The fourth version of the Internet Protocol (IP) whoose address is represented by a 32-bit integer"],
		["IPv6","The sixth version of the Internet Protocol (IP) whoose address is represented by a 128-bit integer"],
		["SNMP","The group of protocols used for managing routers, switches and other network devices"],
		["RFC","The formal document from the Internet Engineering Task Force ( IETF )"],
		["WINS","The equivalent of the DNS in Microsoft Windows network"],
		["BOOTP","The UDP-based protocol used for acquiring the configuration from the server by clients. The predecessor of DHCP"],
		["NetBEUI","The no-routable transport protocol used in Windows operating systems family"],
		["TFTP","The simplified version of the FTP"],
		["NetBIOS","The network protocol designed by IBM which allows you to communicate in TCP/IP networks"],
		["IPX","The network layer protocol derived from the XNS protocol. It was repressed by the IP"],
		["Z39.50","The protocol used for search and retrieval of data from a database over TCP/IP. Maintained by the Library of Congress. A predecessor of REST architecture"],
		["IPsec","The network protocol suite that authenticates and encrypts packets of data sent over the network"],
		["Sinec H1","The communications protocol used within SCADA networks. Developed by Siemens, used in the control infrastructure of CERN"],
		["KA9Q","The popular early implementation of the TCP/IP for amateur packet radio systems and smaller personal computers"],
		["GPRP","The Internet Routing Protocol like IPv4 and IPv6 which uses the spatial position"],
		["Switch","The device that connects computers together into a network by using packet switching to receive, process and foward data to the destination device"],
		["Hub","The physical-layer device that allows the connection of several hosts together into a computer network. Forwards packets to each connected host"],
		["Host","The computer or another device connected to a computer network which is identified by a unique address"],
		["Patch cord","The cable that is used for connecting active devices in the network"],
		["RJ-45","The type of the connector that is commonly used in Ethernet networks"],
		["8P8C","The official name of RJ-45 connector"],
		["AP","The network device used to add the possibility of connecting wireless devices to the network"],
		["SCADA","The industrial system designed to provide information about industrial processes and maintaining automated control in power plants, factories etc."],
		["Modem","The device which modulates signals to send data by a transmission channel, and demodulates signals to retrieve incoming data"],
		["TCP/IP Model","The theoretical layer-based network communication model that consists of 4 layers. The most commonly used model"],
		["Unicast","One-to-one transmission"],
		["Multicast","One-to-many transmission"],
		["Router","The networking device that forwards packets between computer networks"],
		["Broadcast","One-to-all transmission"],
		["Bridge","The computer networking device that creates a single aggregate network from multiple communication networks or network segments for example aggregates different-media networks"],
		["Simplex","The kind of transmission in which data flows only in one direction."],
		["Half-duplex","The kind of transmission in which data flows in both directions but one at time"],
		["Full-duplex","The kind of transmission in which data flows in both directions simultaneously"],
		["Repeater","The electronic device that receives a weak signal and retransmits it with full strength"],
		["VPN","The connection between two networks that is tunneled (and usually encrypted) via another network"],
		["Network adapter","The adapter which connects device to a computer network"],
		["WWW","The part of Internet that operates within commonly known protocols like HTTP. Consists of web pages"],
		["Star network","The network topology which consists of one central node that connects all devices togehter"],
		["Ring network","The computer network configuration where the devices are connected to each other in a circular shape. Each packet is sent around the ring until it reaches its final destination."],
		["Bus network","The network topology in which nodes are directly connected to a common linear half-duplex link called a bus"],
		["Point-to-point","The simplest topology with a dedicated link between two endpoints"],
		["Fully connected network","The network topology in which all nodes are interconnected"],
		["Packet switching","The communications method that groups all transmitted data into packets"],
		["Physical Layer","The lowest layer in the OSI model, responsible for transmitting data bits from one device to the other one by determining clock rates and bits representation"],
		["Data-link layer","The second layer of the OSI model. Responsible for connections handling, integrality checks and determining the route between systems"],
		["Network layer","The third layer of the OSI model. Responsible for routing and control functions providing informations about routes during the packet exchange between networks"],
		["Node","The connection point that can receive, create or send data in network"],
		["Transport layer","The fourth layer of the OSI model. This layer is responsible for setting-up connections and segmentating data acquired from the network layer. Handles connection-oriented and connectionless communication"],
		["Session layer","The fifth layer of the OSI model. It is responsible for creating sessions and provides services responsible for sessions handling and security"],
		["Connection-oriented communication","The network communication model in which communication session is estabilished before any useful data can be transfered"],
		["Connectionless communication","The data transmission method used in packet switching networks in which each data unit is individually addressed and routed"],
		["Print server","The device that connects printers to client computers over a network"],
		["Presentation layer","The sixth layer of OSI model that formats data provided by application and session layer and encrypts data sent from the application layer"],
		["Applications layer","The seventh layer of the OSI model that consists of user's software"],
		["Database server","The computer program that provides database services to other computers"],
		["Mailing list server","The server that manages mailing lists for groups of users"],
		["PM","The modulation based on switching a signal on and off according to bits values"],
		["AM","In this modulation data is mapped into the amplitude of transmitted signal (amplitude above the given threshold is interpreted as logical 1)"],
		["FM","In this modulation data is represented as fluctuation in signal frequency"],
		["SAN","A network which provides access to consolidated, block level data storage"],
		["G band","30 EHz-300 EHz frequency range with 10pm-1pm wavelength"],
		["HX band","3 EHz - 30 EHz range with 100pm - 10pm wavelength"],
		["Interplanetary Internet","The conceived computer network in space, consisting of a set of network nodes that can communicate with each other"],
		["SX band","30 PHz - 3 EHz with 1nm - 100 pm wavelength"],
		["EUV","3 PHz - 30 PHz with 100nm-10nm wavelength"],
		["NUV","300 THz - 3 PHz with 1 ?m - 100 nm wavelength"],
		["NIR","30 THz - 300 THz with 10?m - 1?m wavelength"],
		["MIR","3 THz - 30 Thz with 100 ?m - 10 ?m wavelength"],
		["Broadband","Wide bandwidth transmission which transports multiple signals"],
		["FIR","300 GHz - 3 THz with 1mm - 100?m wavelength"],
		["EHF","30 GHz - 300 GHz with 1cm - 1mm wavelength"],
		["SHF","3 GHz - 30 GHz with 10cm - 1cm wavelength"],
		["UHF","300 MHz - 3 GHz with 100cm - 10cm"],
		["VLSM","A method of IPv4 network adressing in which the length of the subnet mask may vary"],
		["VHF","3 MHz - 300 Mhz with 10m - 1m wavelength"],
		["HF","3 MHz - 30 MHz with 100m - 10m wavelength"],
		["MF","300 kHz - 3 MHz with 1km - 100m wavelength"],
		["LF","30 kHz - 300 kHz with 10km - 1km wavelength"],
		["VLF","3 kHz - 30 kHz with 100km - 10 km wavelength"],
		["VF/ULF","300Hz - 3kHz with 1000km - 100km wavelength"],
		["SLF","30 Hz - 300 Hz with 10000 km - 1000 km wavelength"],
		["ELF","3Hz - 30 Hz with 100000 km - 10000 km wavelength"],
		["STP","The type of cable that is covered with additional layer of the metal wire mesh which protects the cable from the environment noise"],
		["FTP (cable)","The type of cable that is covered with the grounded foil that offers similar protection against environment noise as the STP cable but on a lower scale"],
		["UTP","The basic type of the cable that is used in computer networks. It consists of eight wires"],
		["Coaxial cable","The thick cable with a wire inside that provides wide broadband and high connection availability"],
		["Sneakernet","Non-automated data transmission via USB memory sticks, flash cards etc."],
		["Network topology","Description of the collocation of network elements and associations between them"],
		["Physical topology","It describes physical arrangement of network devices with connections between them"],
		["Logical topology","It is a mapping of paths between nodes in given protocols"],
		["Network Protocol Stack","It is a mapping of the model used to describe network transactions initiated in one device and ending in another"],
		["Encapsulation","The process of joining metadata to data while sending data between layers"],
		["Onion routing","The routing based on encrypting data for the anonymous internet browsing"],
		["Frame Relay","The technology that specifies the physical and data link layers of digital telecommunications channels using packet switching"],
		["WPA","The security standard for devices using wireless connection (Wi-Fi) which encrypts data through the temporal key integrity protocol"],
		["WEP","The security algorithm for IEEE 802.11 wireless networks which uses static encryption key"],
		["LDAP","The protocol designed for using directory services via IP network"],
		["CRC","The algorithm that calculates 32-bit checksum of a message and compares it with the checksum that is stored inside of the packet. Used to detect the data corruption"],
		["Checksum","Fixed-length value calculated from a message for various purposes like security, data integrity checks etc."],
		["Entity (OSI)","Active element located in the OSI layer. It can be a software module or a functional part of a device"],
		["Service Provider","One or multiple entities that communicate with a higher layer of the OSI model"],
		["Service subscriber","The entity that uses services"],
		["SAP (OSI)","The address used for connecting to the service provider"],
		["IDU (OSI)","A piece of data that is sent between two entities via SAP"],
		["SDU (OSI)","A unit of data that has been passed down from an OSI layer to a lower layer and has not been encapsulated yet"],
		["PDU (OSI)","A unit of data that is created when a layer of the OSI model needs additional operations (like fragmentation) on data. It is composed with a header determining its position in stream or properties"],
		["PSTN","The most commonly used telephone network standard. Consists of POTS and ISDN services"],
		["POTS","The oldest telephone service. It is the analog voice transmission in 300-3400 Hz frequency range with DTMF signaling system"],
		["ISDN","The technology that allows usage of old PSTN networks for providing access to new digital services"],
		["DTMF","Signaling system used in old telephone networks. It is used to send control commands via telephone networks using audio tones (you can hear those commands as sounds in your phone)"],
		["WMI","The technology used in publishing information about the host and receiving information from other hosts in Windows networks"],
		["Multiplexing","It's a technique of sending several signals through one transmission medium"],
		["Bandwidth","The difference between the highest and the lowest frequency"],
		["VoIP","The technology used in transfering voice via the Internet Protocol"],
		["Baud","Number of distinct signal changes within transmission medium"],
		["TDM","Multiplexation that divides stream of data using time frames. A chunk of data that corresponds to given time-frame is sent by the transmission medium"],
		["TDMA","Sharing one TDM network between many transmitters"],
		["QoS","Description of overall performance of Network, Telephony or Cloud Computing services"],
		["MAU","Device which allows you to connect multipe devices in a star topology"],
		["E-carrier","Technology of transmiting voice, replaced by the Ethernet"],
		["FDM","Multiplexation that divides stream of data into different frequencies carried by a transmission medium"],
		["FDMA","Sharing one FDM network between many transmitters"],
		["T1","The digital telephone standard which is able to transmit up to 24 multiplexed voice"],
		["WDM","Multiplexation that divides stream of data into several rays with different wavelengths. Commonly used in fiber-optic networks"],
		["Jitter","Deviation from true periodicity of signal resulting in local change of amplitude, frequency or phase"],
		["ADM","A kind of multiplexer used in in fiber-optic networks. Based on FP interferometer used to separate or join beams of light"],
		["ROADM","The configurable version of ADM multiplexer. Often used in metropolitan area networks (MANs)"],
		["Wander","The phenomenon similar to Jitter, but it cannot be damped. It concers clock signals"],
		["MIMO","Communication channel created using signal polarization. It allows transmission of more than one data streams through one medium. Commonly used in SatTV"],
		["Polarization","The property applying to transverse waves that specifies the geometrical orientation of the oscillations"],
		["FHSS","The technology of multiplexation which uses rapidly changing frequency of the carrier signal in pseudorandom manner. Transmitter and receiver know the order of frequencies, but for other devices this transmission is a noise"],
		["DMZ","The subnetwork that separate LAN from other networks. Servers and services are located inside it, so there is access from internet but the local network is unreachable"],
		["ISP","The company that provides access to the Internet for a fee."],
		["NAT","It is a process where a network device, usually a NAT server, assigns a public address to a computer (or group of computers) inside a private network"],
		["DCE","These are computer hardware devices used to establish, maintain and terminate communication network sessions between a data source and its destination"],
		["DTE","It is an end instrument that converts user information into signals or reconverts received signals"],
		["DRM","These are various access control technologies that limit the usage of digital content and devices"],
		["DoS","Any type of attack where the attackers (hackers) attempt to prevent legitimate users from accessing the service by blocking it with multiple requests"],
		["DDoS","It is a type of computer attack that uses a number of hosts to overwhelm a server, causing a website to experience a complete system crash"],
		["AD","It is the Windows OS directory service that facilitates working with interconnected, complex and different network resources in a unified manner"],
		["EGP","It is an obsolete routing protocol that was used for data exchange between neighboring gateway hosts in autonomous systems"],
		["BGP","It is a routing protocol used to transfer data and information between different host gateways, the internet or autonomous systems"],
		["IGP","It is an Interior Gateway Protocol that uses packet-switched networks to support efficient autonomous system routing for internet service providers and large enterprises"],
		["EIGRP","It is an advanced distance vector routing protocol based on the principles of the Interior Gateway Routing Protocol (IGRP)"],
		["OSPF","It is a link state routing protocol (LSRP) that uses the Shortest Path First (SPF) network communication algorithm (Dijkstra's algorithm) to calculate the shortest connection path between known devices"],
		["RIP","It is a dynamic protocol used to find the best route or path from end-to-end (source to destination) over a network by using a routing metric/hop count algorithm"],
		["IS-IS","It is a dynamic class routing protocol used by autonomous system routers running on TCP/IP hosts"],
		["IGRP","It is a proprietary distance vector routing protocol used to communicate routing information within a host network"],
		["TOE","A technique of transferring tasks related to TCP stack computations from the CPU to the NIC"],
		["VIA","The abstract model of a user-level zero-copy network used for standardize the interface for high-performance network technologies"],
		["HPC","It is a definition used to describe systems characterised by high computational performance or high speed of output data generation"],
		["InfiniBand","The standard of the open serial multichannel I/O interface with a high speed and a short latency time"],
		["NDR","It is a version of InfiniBand with the highest transmission rate"],
		["SETI@Home","It is a volunteer project which purpose it to analyze radio signals, searching for signs of extraterrestrial intelligence etc. Anybody can participate in SETI@Home program."],
		["Twinax","A type of coaxial cable with two conductors instead of one. Used in a short-distance high speed applications"],
		["GAMMA","It is a low-latency protocol for Gigabit Ethernet clusters running Linux"],
		["RDMA","The technology that allows computers in a network to exchange data in main memory without involving the processor, cache or operating system of either computer"],
		["iWARP","The extended version of the VIA for IP networks"],
		["Cluster","A set of connected computers that can be viewed as a single computer system"],
		["SCTP","It is a transport-layer protocol similar to the UDP and TCP protocol"],
		["Lockstep","It is a technology that uses replicated, fault-tolerant hardware components that process the same instructions at the same time.Developed by the Stratus ©"],
		["SOA","It is a style of software design where services are provided to the other components by application components, through a communication protocol over a network"],
		["Beowulf Cluster","A computer cluster that consists of identical off the shelf computer connected within a small LAN with installed libraries allowing it to perform parallel computations"],
		["MPI","It is a specification for the developers and users of message passing libraries."],
		["PVM","A software system designed to allow a network of heterogeneous machines to be used as a single distributed parallel processor"],
		["AAA Server","It is a device that hosts a AAA service which is responsible for handling user requests for access to a network"],
		["ASA","It is a family of firewall devices produced by Cisco that incorporates the multilayer security"],
		["TCB","The set of all hardware and software components that are critical to computer system's security"],
		["MSG","Software or hardware appliance used to provide a secure communication between a mobile application and backend resources within a company network"],
		["PUF","A value that cannot be cloned. It is used to fingerprint semiconductor circuits like microprocessors. Examples are structural variations within semiconductor or specially designed integrated circuits"],
		["HSM","A computing device that provides cryptoprocessing functionalities such as encryption, key management and generation"],
		["SSL Accelarator","A device that offloads PKI-related computation for TLS and SSL and thus reduces a CPU usage"],
		["Secure Cryptoprocessor","A special SoC solution used to perform specyfic cryptographic function. They are usually built as impenetrable black-box modules"],
		["Impenetrable device","A device that is cased with multiple infiltration-resistant layers like epoxide layers that make penetration or analysis of this device almost impossible without destroying its structure"],
		["Security token","A physical device that grants access to a restricted resource. It can be a stick which display time-determined access codes that are compared with codes generated by a server at the same time. Used in a 2FA"],
		["Disconnected token","A security token which generates access code without an active connection to the authorization system. For example a RSA SecurID"],
		["Connected token","A security token which must be connected to the authorization device (like laptop to which we are trying to log in). For example smart card solutions, mobile phones with authorization via USB app etc."]
	],
	[
		["2252679"], //Advanced English C1-C2 (audio) vol. 1
		["Tom, Dick and Harry","everyone or anyone, an ordinary, undistinguished or common person/people taken at random"],
		["fit as a fiddle","very healthy and strong, as right as rain, as sound as a bell"],
		["speak of the devil","something you say when the person you were talking about appears unexpectedly"],
		["think outside the box","think creatively, differently, unconventionally, or from a new perspective"],
		["no strings attached","without hidden commitments, may refer to formal agreements or to casual sex between friends"],
		["have a small bladder","you say this about a person who often needs to go to the toilet"],
		["he who pays the piper calls the tune","a proverb meaning that the person who provides the money for something has the right to determine how it's spent"],
		["let sleeping dogs lie","a proverb said to warn someone that they should not talk about a bad situation that most people have forgotten about"],
		["leave somebody in the lurch","abandon somebody and leave them in a difficult situation"],
		["cut somebody some slack","allow someone some leeway in their conduct"],
		["know the ropes","be familiar with a place or organization and able to act effectively within it"],
		["talk turkey","discuss something honestly and directly"],
		["aid and abet","help and encourage, usually in the commission of a crime or anti-social act"],
		["across the pond","on/to the other side of the Atlantic Ocean"],
		["stepping stone","an event or experience that helps you achieve something else"],
		["friends with benefits","people who have sex without any commitment and they are not going to be a couple"],
		["get cold feet","suddenly become too frightened to do something one had planned to do"],
		["apples and oranges","something you say when two items or groups of items are compared that cannot be practically compared"],
		["water under the bridge","what has happened, has happened"],
		["show somebody the ropes","show someone how to do a job or activity correctly, instruct them to perform a task in a professional way"],
		["err on the side of caution","act in the least risky manner in a situation in which one is uncertain about the consequences"],
		["be at the end of the rope","have no more patience or strength"],
		["be on a fence","be unable to make a decision or take a side when presented with two options or possibilities; undecided"],
		["beat around the bush","avoid talking about what is important or telling the truth"],
		["hat in hand","humbly asking for a favour"],
		["snug as a bug in a rug","safe, warm and cosy, comfortable"],
		["be calling the shots","be the boss, rule, be in charge"],
		["be cruising for bruising","said about someone who is likely to become physically assulted for their actions"],
		["hold the candle to someone","be as good or as desirable as someone"],
		["eat humble pie","apologize humbly, in humiliation, admit that you were wrong"],
		["enter the fray","join a competition"],
		["two a penny","very cheap or very common, and therefore not valuable"],
		["do someone a solid","do something for someone as an act of kindness; do someone a favour (informal American)"],
		["put something on a back burner","make something a low priority, give it little or less thought or attention"],
		["steal one's thunder","garner the attention or praise that one had been expecting, steal the show"],
		["Bob's your uncle","another way of saying 'you are all set', 'you've got it made', 'there it is', 'there you have it' or 'piece of cake', typically, said to conclude a set of simple instructions or when a result is reached"],
		["jack of all trades","a handyman, person able or employed to do occasional domestic repairs and minor renovations, skilled in many areas, sometimes also derogatory"],
		["Jack and Jill","used to describe an average man and woman, refers to an old nursery rhyme"],
		["slippery slope","a course of action that seems to lead inevitably from one action or result to another with unintended consequences"],
		["give somebody a heads up","to tell someone that something is going to happen"],
		["skinny-dipping","swimming naked"],
		["spend a penny","to urinate, used euphemistically"],
		["pull some strings","to influence someone to get something done"],
		["call an audible","to change plans suddenly in order to adapt to present circumstances, originally referring to American football"],
		["aunt Irma visiting","a euphemism used in The IT Crowd to refer to having a menstrual period"],
		["out of the blue","completely unexpected"],
		["nip in the bud","stop something at an early stage"],
		["be as thick as thieves","describes a relationship between people that is very close"],
		["fall off the wagon","start drinking alcohol again after a period when you have been sober"],
		["have a knack for something","be exceptionally good at doing something"],
		["join the mothball","go out of date and be retired, usually used about weapons or fleet that might yet be recalled to service"],
		["cut to the chase","get to the point without wasting time"],
		["spitting game","using humour and charm to show you are interested in a particular woman"],
		["apple of one's eye","something or someone very precious or dear, loved above all others, someone's favourite person or thing"],
		["music to one's ears","something that is very pleasant to hear"],
		["until the cows come home","for a long but indefinite time"],
		["hit a snag","encounter an unexpected obstacle or problem"],
		["off the grid","untraceable through any means of commerce or communication that could be linked to one's identity"],
		["sitting duck","an easy or defenseless target"],
		["in the thick of things","very busy, in the middle of or preoccupied with something or several things"],
		["have a leg to stand on","have something to lean on, to begin with (usually negative)"],
		["hold a grudge against someone","harbour persistent and continual resentment or ill feelings toward someone, not let it go when you feel someone's insulted or wronged you"],
		["be in the loop","have the special knowledge or power that belongs to a particular group of people"],
		["be right on the money","be completely right and accurate, an expression originally used to describe a bet which turned out to be exactly right"],
		["burn the candle at both ends","to work extremely or excessively hard; to work too hard for good health or peace of mind"],
		["call it quits","to stop doing something; to agree with someone that a debt has been paid and that no one owes anything more"],
		["dodge a bullet","to have a narrow escape; to avoid injury, disaster, trouble"],
		["feel blue","feel depressed or sad, have the blues"],
		["for a song","for a very low price; very cheaply"],
		["get the wrong end of the stick","to misunderstand a situation"],
		["have a lot on the plate","to have a large number of problems to deal with or a large amount of work to do"],
		["have second thoughts","to change your opinion about something or start to doubt it"],
		["have ants in the pants","to be unable to sit still, due to anxiety, excess energy or impatience"],
		["bury the hatchet","to stop fighting or arguing, to reach an agreement or at least a truce"],
		["let the cat out of the bag","to allow a secret to be known, usually without intending to"],
		["have a frog in one's mouth","to be unable to speak normally because one's throat is dry and hoarse"],
		["elephant in the room","an obvious problem or difficult situation that people avoid talking about"],
		["make the cut","to succeed at something or meet a requirement; to be chosen out of a field of candidates or possibilities"],
		["miss the cut","to fail to match or better the score necessary to remain in the tournament, thus resulting in elimination, to be rejected"],
		["give no quarter","to show no mercy; originally, in military, to take no prisoners"],
		["out of line","behaving in a way that breaks the rules or is considered inappropriate, beyond what is considered acceptable behavior"],
		["lose the plot","to no longer be able to act normally or understand what is happening"],
		["make peace with","to reconcile with or accept something that previously was a source of stress or conflict"],
		["come to terms with","to gradually accept a sad situation, often the death of someone you love"],
		["read the riot act","to speak angrily to someone about something they have done and warn that person that they will be punished if it happens again"],
		["it goes without saying","an expression meaning that something is perfectly clear, obvious or self-evident, commonly acknowledged, established, or accepted"],
		["run a tight ship","to be very strict in controlling a business, managing an organization or operation"],
		["make ends meet","to have enough money to afford everything that you need"],
		["upset the apple cart","to ruin or interfere with one's plans or goals, to mess up or ruin something"],
		["through thick and thin","in both good and bad times"],
		["pay through the nose","to pay a very high price for something, more than is fair or reasonable, pay an arm and a leg"],
		["get out of one's hair","to no longer be pestering or annoying to someone, to not be one's responsibility or burden any longer"],
		["feather in one's cap","figuratively, an achievement to be proud of"],
		["see eye to eye","to agree fully; to have the same opinion"],
		["bring someone up to speed","to give someone all the latest information about something"],
		["take one for the team","to sacrifice one's own welfare or interests in favour of others"],
		["winner winner chicken dinner","a phrase used to convey a positive outcome, exclaimed to celebrate a victory, especially in gambling"],
		["done like a dinner","completely defeated, often unfairly, in a contest or competitive situation, having failed or lost, Australian English"],
		["done up like a dog's dinner","wearing very formal or decorative clothes in a way that attracts attention, not suitable for the occasion"],
		["let bygones be bygones","to stop focusing on something that happened in the past (usually a source of conflict or tension)"],
		["see the writing on the wall","to notice and interpret apparent signs or indications that something will or is about to happen in the future, especially something bad or unfortunate"],
		["go for the jugular","to attack in the most aggresive way possible or where the victim is most vulnerable, the term is almost never used to refer to physical violence"],
		["grow a pair","to start acting in a strong, confident, and courageous manner, to stop being a pussy"],
		["have a gippy tummy","suffer from stomach pains and diarrhoea, especially while on holiday"],
		["like shooting fish in a barrel","ridiculously easy to accomplish, win, beat, defeat or kill"],
		["cat got your tongue","something you say to someone when you are annoyed or surprised because they will not speak"],
		["put two and two together","to draw an obvious conclusion from what is known or evident"],
		["hear it on the grapevine","to learn of something through an informal means of communication, especially gossip"],
		["let one's hair down","to allow yourself to behave much more freely than usual and enjoy yourself; old-fashioned, informal"],
		["gird up one's loins","to prepare and strengthen oneself for future actions, typically ones that may be dangerous or difficult"],
		["get one's knickers in a twist","to become overly upset or emotional over something, especially that which is trivial or unimportant"],
		["neck of the woods","informal, the area someone comes from; the surrounding neighbourhood; a place in which one is comfortable or with which one is familiar"],
		["set the bar high","to establish an expected, required, or desired standard of quality"],
		["strike while the iron is hot","to make most of an opportunity or favorable conditions while one has the chance to do so"],
		["make hay while the sun shines","to make good use of an opportunity while it lasts, also: strike while the iron is hot"],
		["as the crow flies","used to say that a distance is measured in a straight line between two points or places"],
		["mum's the word","said when you tell someone, or agree with someone, to keep something a secret"],
		["put one's foot down","to use your authority to stop something happening"],
		["jumping the shark","reaching a point where a television show stops becoming more popular or starts to decrease in quality"],
		["off the bat","immediately, at once, without delay, without hesitation, first thing, a term related to baseball, right off the bat"],
		["not by a long shot","by no means, not a remote chance"],
		["catch one's drift","to understand the meaning, insinuation, or implication of what one is saying"],
		["pass the buck","to shift or reassign the blame or responsibility for something to another person, group, or thing"],
		["catch a break","to obtain or receive a convenient, beneficial, and/or lucky opportunity"],
		["take the edge off something","to make something unpleasant have less of an effect on someone"],
		["over a barrel","in a position of vulnerability, weakness, or powerlessness, out of one's control"],
		["have a handle on something","to have a firm, clear understanding or determination of something"],
		["have a bone to pick with someone","to want to talk to someone about something annoying they have done"],
		["cop a feel","fondle someone sexually, especially in a surreptitious way or without their permission"],
		["between a rock and a hard place","in a very difficult situation, faced with two equally undesirable alternatives"],
		["walk on eggshells","to be extra-careful when speaking to someone, in order not to make them angry"],
		["push the envelope","approach or extend the limits of what is possible"],
		["misery loves company","people who are unhappy like to share their troubles with others"],
		["it never rains but it pours","misfortunes or difficult situations tend to follow each other in rapid succession or to arrive all at the same time"],
		["needle in a haystack","something hard to find"],
		["wipe the floor with someone","inflict a humiliating defeat on a person"],
		["when the going gets tough","when it becomes difficult to continue or to make progress"],
		["whatever floats your boat","a phrase that often means whatever soothes your soul or whatever works best for you"],
		["take it down a notch","instruction to an individual to regulate his or her level of enthusiasm / to be less intense, serious, or extreme"],
		["take the high road","to do the right thing even if its not popular or easy"],
		["cut the apron strings","to break free from dependency on another person"],
		["first come first served","used to mean that people will receive something or be dealt with in the order in which they ask or arrive"],
		["knock one's lights out","to punch someone until he or she is unconscious"],
		["walk the left-hand path","to use black magic for evil and selfish purposes"],
		["walk the right-hand path","to use white magic for selfless purposes"],
		["wait for the other shoe to drop","to expect a seemingly inevitable event, especially one that is not desirable"],
		["the odds are","it is probable that"],
		["be the dead spit of","to look exactly like someone else"],
		["wild goose chase","a prolonged or chaotic search for something that is difficult to find (often because it does not exist)"],
		["rough around the edges","unpolished, imperfect, somewhat lacking in refinement, sophistication, manners, etc."],
		["give it a shot","to try something (often for the first time as a means of forming an opinion about it)"],
		["the grass is always greener","other people's circumstances or belongings always seem more desirable than one's own"],
		["no can do","used in speech to say that one cannot do something they have been asked or told to do"],
		["gloves are off","usually used to describe a dispute or fight, when people are beginning to behave in a more hostile or tenacious way"],
		["burn the midnight oil","to stay up late working on a project or task"],
		["that ship has sailed","some possibility or option is no longer available or likely"],
		["take the red eye","to take an overnight flight that arrives at its destination very early in the morning"],
		["close but no cigar","a narrowly missed success, a phrase said when one is almost correct or successful but ultimately fails"],
		["line in the sand","a limit beyond which someone cannot go without suffering serious consequences, a set limit which has to be adhered to strictly"],
		["friend of Dorothy","in gay slang, a gay man or any LGBTQ person"],
		["square up","pay someone the money that you owe them"],
		["waffle on","speak or write at length in a vague or trivial manner, without saying anything useful or interesting"],
		["water down","literally: thin down, dilute; metaphorically: make something weaker or less effective"],
		["hand something off","give responsibility for something to someone else, give something to someone else to do or complete"],
		["haggle over something","argue about details of something (often about price)"],
		["do in","to exhaust, to tire out, to damage or injure, to kill or end"],
		["duck down","to crouch in an attempt to hide or protect oneself"],
		["add up","to seem reasonable or likely, make sense"],
		["fizzle out","to gradually end, often in a disappointing or weak way, slowly over time"],
		["giddy-up","an exclamation said to make a horse start moving or go faster"],
		["the early bird catches the worm","a proverb said to advise someone that they will have an advantage if they do something immediately or before anyone else does"],
		["a fool and his money are soon parted","foolish people make purchases without consideration"],
		["the penny has dropped for him","he finally understood"],
		["when the cat's away the mice will play","a proverb meaning that when the person who is in charge of a place is not there, the people there behave badly"],
		["there's more than one way to skin a cat","a saying meaning there are many ways to do something, there are many ways to achieve a goal"],
		["absence makes the heart grow fonder","a saying meaning that when people we love are not with us, we love them even more"],
		["don't count your chickens before they hatch","a proverb saying you should not make plans based on something that's yet to happen"],
		["still waters run deep","a calm and shy person may often surprise with behavior that no one would expect"],
		["all work and no play makes Jack a dull boy","a proverb meaning that without time off from work, a person becomes both bored and boring"],
		["a bird in the hand is worth two in the bush","used for saying that it's better to hold onto something one has already than to risk losing it by trying to attain something better"],
		["half a loaf of bread is better than none","something is better than nothing, even if it is less than one wanted"],
		["it's swings and roundabouts","disadvantages and failures in one field are compensated by advantages and progress in other fields"],
		["easy come, easy go","said when something, especially money, is easily got and then soon spent or lost"],
		["too many cooks spoil the broth","said when there are too many people involved in trying to do the same thing, so that the final result will not be good"],
		["time heals all wounds","said to mean that a painful or difficult situation will seem less bad as time passes"],
		["the end justifies the means","a positive outcome justifies the methods one employs to reach it, even if they are unethical"],
		["when there's a will there's a way","if someone is determined to do something, he will find a way to accomplish it regardless of obstacles"],
		["daffodil","a man who is in love with himself"],
		["vehemently","in a strong and emotional way"],
		["smart alec","a nicer way to say smart ass, a person who is irritating because they behave as if they know everything"],
		["blood drive","an event, usually charitable, in which people are requested to donate blood"],
		["conundrum","a problem that is difficult to deal with or a riddle containing a word pun"],
		["childminder","another word for a babysitter, a person who looks after children in their own home for payment"],
		["footloose","free to do what you like and go where you like because you have no responsibilities"],
		["windfall","an amount of money that you get that you did not expect or a piece of fruit blown down from a tree"],
		["shit on a shingle","a classic American military dish; creamed, chipped beef on a toast"],
		["John Hancock","signature (an expression reffering to the Declaration of Independence)"],
		["kludge","workaround or quick-and-dirty solution that is clumsy"],
		["vapid","dull, boring"],
		["sugarcoat","make something seem more positive or pleasant than it really is"],
		["fortnight","a period of two weeks"],
		["flabbergasted","feeling shocked, speechless, usually because of something you were not expecting"],
		["candour","the quality of being honest and telling the truth, especially about a difficult or embarrassing subject"],
		["crass","showing no intelligence or sensitivity"],
		["pitchy","sooty, of the blackest black, similar to the colour of coal"],
		["embezzlement","secretly taking money that is in your care or that belongs to an organization or business you work for"],
		["clemency","mercy, mercifulness, kindness when giving a punishment"],
		["shoddy","badly and carelessly made, rundown, shabby, made of or containing inferior material"],
		["yahoo","a rude, loud, unpleasant person who has very little education and culture, as if they were raised in a barn, a bumpkin, hayseed, hick, rube, yokel, or hillbilly"],
		["leeway","freedom to do what you want within particular limits, the sideways drift of a ship to leeward of the desired course"],
		["collect call","telephone call in which the calling party wants to place a call at the called party's expense"],
		["without a hitch","with no problem(s), used about an event or process to describe how smoothly everything went"],
		["tomato tomato","whatever, it does not make any difference"],
		["to a T","perfectly, properly, completely, exactly, sometimes said about fitting clothes or suiting colour"],
		["argy-bargy","loud argument or discussion, Br. E."],
		["bamboozle","to con, defraud, trick, make a fool of, humbug or impose on someone, also confuse, frustrate or perplex someone"],
		["doxxing","searching for and publishing private or identifying information about a particular individual on the internet, typically with malicious intent"],
		["swatting","making a hoax call to the emergency services in an attempt to bring about the dispatch of a large number of armed police officers to a particular address"],
		["willy-nilly","suddenly and without planning or order, if something happens like that, it happens even if the people who are involved do not want it to happen"],
		["nitty-gritty","the most important and basic facts or details about something"],
		["varsity","a team representing a college or university"],
		["bridge and tunnel people","a pejorative term for people who commute into Manhattan from surrounding communities"],
		["lightning conductor","a long thin piece of metal on top of a building that attracts lightning and allows it to reach the ground safely"],
		["itinerary","a detailed plan for a journey, especially a list of places to visit"],
		["dog eat dog","a situation in which people compete very hard and will do anything to be successful"],
		["johnnie","a UK slang word for condom, also rubber, traditionally referred to a loose short-sleeve gown opening in the back, worn by patients undergoing medical treatment or examination"],
		["cunnilingus","an oral sex act performed by a person on the female genitalia"],
		["anilingus","an oral and anal sex act in which a person stimulates the anus of another by using the mouth, including lips, tongue, or teeth, also called rimming, a rim job or tossed salad"],
		["cotton mouth","dryness of the mouth, also known as xerostomia, occurs when salivary glands don't make sufficient saliva to prevent the drying of the mouth"],
		["serendipity","a fortunate occurrence and development of events by chance in a happy or beneficial way"],
		["heartburn","a problem created by acid reflux, creating a burning pain in the lower chest"],
		["pulchritudinous","of Latin origin, a synonym of beautiful, only used about people"],
		["stolid","calm, dependable, and showing little emotion"],
		["exacerbate","make something bad even worse"],
		["goldbricking","inventing excuses not to work as much as someone is able to"],
		["foment","heavily encourage to take actions such as rebellion or riot"],
		["glitch","a sudden, usually temporary malfunction or fault of equipment"],
		["cul-de-sac","a dead-end street, particularly one with a circle for turning around at the end"],
		["preposterous","extremely stupid, ridiculous, absurd"],
		["procasturbate","masturbate in order to put doing something off"],
		["teetotaller","an abstainer, someone who never drinks alcohol and is always sober"],
		["avarice","a strong feeling that you want to have a lot of money and possessions and keep them for yourself, greed"],
		["crow's nest","a shelter or platform fixed at the masthead of a vessel as a place for a lookout to stand"],
		["impromptu","improvised, done or said without earlier planning or preparation"],
		["ambidextrous","able to use both hands equally well"],
		["an iota of something","an extremely small amount of something"],
		["midwife","a person, usually a woman, who is trained to help women when they are giving birth"],
		["down-to-earth","with no illusions or pretensions, practical and realistic"],
		["eviscerate","take out the entrails, disembowel"],
		["fit","healthy and strong, suitable for a particular purpose or activity, in UK slang: sexually attractive, hot"],
		["diddums","oh poor you"],
		["smarmy","polite in an unpleasant or insincere way"],
		["tits","an exclamation used to express that something is cool and awesome"],
		["chop-chop","used for telling someone to hurry, just like hurry up, come on, get a move on etc."],
		["obnoxious","very unpleasant, offensive or rude"],
		["oomph","enthusiasm, vitality, power, energy"],
		["stasis","inactive, low metabolic torpor state for mission transit phases"],
		["benign","referring to a tumor it describes a growth which is not cancer and is not likely to be harmful"],
		["bibble-babble","idle talk, prating to no purpose, a rare and archaic word"],
		["blank slate","something clear and empty, somebody free from preconceptions and biases, not affected by any ideology"],
		["in dire straits","in a very bad situation that is difficult to fix, in a difficult position"],
		["bogeyman","a mythical creature in many cultures used by adults or older children to frighten bad children into good behavior"],
		["whistle-blower","a person who tells someone in authority about something illegal that is happening, especially in a government department or a company"],
		["cry on cue","weep on demand, as if planned to happen exactly at that moment"],
		["binge","a period of excessive indulgence in an activity, especially drinking alcohol or eating"],
		["bokeh","the effect of blurriness in the areas of an image that fall outside a photograph's depth of field"],
		["brouhaha","a lot of noise or angry complaining about something, old-fashioned and informal"],
		["easy-peasy","very easy, simple, informal or childish UK adjective"],
		["consturbation","continuous excessive masturbation, addiction to masturbation"],
		["even-steven","used in reference to fair and equal competition or distribution of resources; having nothing due, or no balance of debt on either side"],
		["facetious","not serious about a serious subject, in an attempt to be funny or to appear clever"],
		["flatline","to die, to stay at the same level, without development, refers to a continuous horizontal line displayed on an ECG or EEG, indicating death"],
		["frenemy","a person with whom one is polite and on friendly terms, despite a fundamental dislike or rivalry"],
		["gardening leave","a period of time after an employee leaves a job when they continue to be paid but are not allowed to go to work or to begin a new job"],
		["glib","fluent but insincere and shallow, speaking or spoken in a confident way, but withoutcareful thought or honesty"],
		["gung-ho","extremely enthusiastic about doing something, especially going to war"],
		["gurney","a light bed on wheels, used to move patients in a hospital"],
		["harried","stressed, rushed, panicked, overly busy or preoccupied"],
		["subpoena","a legal document ordering someone to appear in a law court"],
		["ire","anger, fury, rage, wrath"],
		["jaywalking","crossing a street away from a designated crossing or to walk in the part of the street intended for vehicles rather than on the sidewalk"],
		["pernicious","having a very harmful effect or influence, often in a way that you do not notice easily"],
		["in spades","in large amounts or to a very great degree"],
		["hearsay","information that was heard by one person about another that cannot be adequately substantiated, an out-of-court statement offered in court, which is normally inadmissible because it is not subject to cross-examination"],
		["hefty","heavy, weighing a lot, strong and bulky, impressive, mighty, heavily built"],
		["high-handed","bossy, using power or authority more forcefully than is needed, without thinking about the feelings or wishes of other people"],
		["humongous","informal, of an extremely large size"],
		["imp","a small devil-like creature, evil spirit, a child that behaves badly"],
		["be jonesing","suffer from withdrawal, or otherwise be in desperate, addiction-like need of a substance"],
		["pied-à-terre","a temporary or second lodging in a city that you own or rent in addition to your main home"],
		["gentile","non-Jewish, heathen, pagan"],
		["bedlam","a place or situation of chaotic uproar, and where noise and confusion prevail, historically a lunatic asylum in London"],
		["jumping jack","a physical exercise performed by hopping to a position with the legs spread wide and the hands touching overhead and then returning to a position with the feet together and the arms at the sides, also a toy figure of a person, with jointed limbs"],
		["kerfuffle","UK informal, a disorderly outburst, disturbance, commotion, or tumult, brouhaha, noise, excitement, argument"],
		["jazzy","very bright and colourful, flashy, showy"],
		["kick the bucket","informal, to die"],
		["klick","military slang for kilometre"],
		["lampoon","satire, mockery, ridicule, a piece of writing, a drawing, etc. that criticizes a famous person or a public organization in a humorous way"],
		["loose end","unfinished details, incomplete business, something that still needs to be done or explained"],
		["leg it","to run away very quickly, to hurry, to flee"],
		["non-potable","not suitable for drinking, unsafe, usually about water"],
		["no-brainer","an easy or obvious conclusion, decision, solution, task, etc.; something requiring little or no thought"],
		["affidavit","a written statement confirmed by oath or affirmation, for use as evidence in court"],
		["preesh","an abbreviated, sometimes exclamatory or ironic, form of appreciate"],
		["snail mail","conventional postal delivery service"],
		["ricer","a utensil with small holes through which boiled potatoes are squashed, also refers to a person who makes unecessary modifications to their car"],
		["pentimento","an alteration in a painting, made by an artist himself or another artist later"],
		["palimpsest","a manuscript on which two or more successive texts have been written, each one being erased to make room for the next"],
		["pedestrian","lacking in vitality, imagination, distinction; commonplace, prosaic or dull, also referring to a person walking on foot"],
		["peruse","read through thoroughly; examine in detail"],
		["modesty panel","a thin board of wood or metal attached to the front of a desk, intended to shield legs, ankles, or feet from view"],
		["valet parking","a service provided at a club or restaurant or airport etc. whereby a car is left at the entrance and an attendant parks and retrieves it"],
		["vaporware","a product, typically computer hardware or software, that is announced to the general public but is never actually manufactured nor officially cancelled"],
		["ventriloquist","an entertainer who performs a dramatic or musical work for an audience, projecting the voice into a wooden dummy"],
		["proselytize","to attempt to convert someone to one's own religious faith; to attempt to persuade someone to join one's own political party or to espouse one's doctrine"],
		["pub crawl","a visit to several pubs, one after the other, having a drink or drinks at each one"],
		["mawkish","excessively or falsely sentimental; showing a sickly excess of sentiment; maudlin; sickening or insipid in taste or smell"],
		["lazy Susan","a circular piece of wood or plastic on a base that is put on a table and can be turned around so that everyone can reach the food that is on it"],
		["gamekeeper","a person employed, as on an estate or game preserve, to prevent poaching and provide for the conservation of wild animals"],
		["heyday","the stage or period of greatest vigor, strength, success, etc.; prime"],
		["obstinacy","the quality of being unreasonably determined, especially to act in a particular way and not to change at all, despite what anyone else says, stubborness"],
		["valedictorian","the student with the best grades who usually delivers the valedictory address at commencement"],
		["salutatorian","the student with the second highest academic achievement, who delivers a speech of greeting at a graduation ceremony"],
		["amalgamation","a consolidation or merger, as of several corporations; the production of a metal alloy of mercury"],
		["cantankerous","Ill-tempered and quarrelsome; disagreeable; difficult to handle, arguing and complaining a lot"],
		["stupendous","very surprising, usually in a pleasing way, especially by being large in amount or size"],
		["predicament","an unpleasant situation that is difficult to get out of; in logic: one of the basic states or classifications described by Aristotle into which all things can be placed"],
		["orientation","introductory instruction, training or preparation for a new job or activity, e.g. for incoming students, comes after induction and is a longer, two-way process, involving integration and assimilation"],
		["august","having great importance and especially of the highest social class"],
		["belligerent","hostile and agressive"],
		["halcyon","calm, mild, serene, when combined with 'days' it means idyllic"],
		["gatecrash","to go to a party or other event when you have not been invited"],
		["dawdle","to do something or go somewhere very slowly, taking more time than is necessary"],
		["providence","an influence that is not human in origin and is thought to control people's lives"],
		["topsy-turvy","turned upside down, in or into a state of confusion or disorder"],
		["salacious","having an excessive interest in sex, lustful"],
		["parousia","a one-word term to refer to the second coming of Jesus Christ"],
		["Pentecost","in Christianity, the seventh Sunday after Easter, commemorating the descent of the Holy Spirit upon the disciples; in Jewish tradition, in the Jewish religion, a holy day that comes 50 days after Passover"],
		["gallivanting","going about in search of pleasure or amusement, gadding about, wandering, roaming"],
		["be game","to be ready for action; to be agreeable to participating in something; to be willing to do something"],
		["chum the water","to dump bait or something into the water to attract fish"],
		["hearse","a vehicle for conveying a coffin to a church or cemetery"],
		["lackadaisical","lazy or idle, especially in a dreamy way, characterized by a lack of effort, care, or involvement"],
		["snuffbox","a hollow at the bottom of the thumb, near the edge of the hand, or a small, often decorated box with a hinged lid"],
		["in a jiffy","immediately, very quickly, at once"],
		["effeminate","unmanly, having or showing qualities or characteristics more often associated with females than males"],
		["diaphanous","sufficiently thin or airy as to be translucent, usually used about fabrics such as silk"],
		["tater tots","an American side dish made from deep-fried, grated potatoes"],
		["estuary","the wide part of a river at the place where it joins the sea"],
		["lenient","not as severe or strong in punishment or judgment as would be expected"],
		["swag","promotional items, especially when given for free at an event"],
		["flat-out","in a direct manner, bluntly, outright, completely, utterly, as fast as possible, without any hesitation or concern"],
		["cahoots","close, often secretive or conspiratorial cooperation with someone"],
		["joust","to compete, especially for power or control, in the past to fight with a lance on a horse"],
		["incongruous","unusual or different from what is around or from what is generally happening, not suited to circumstances, lacking consistency"],
		["switcheroo","an unexpected change, especially one in which one thing or person is quickly or secretly exchanged for another"],
		["vociferous","offensively loud and insistent, expressing their opinions and complaints loudly and repeatedly"],
		["upsy-daisy","an informal exclamation to acknowledge a mistake, also said to young children when they fall over"],
		["ironclad","solid or certain; not able to be disputed or questioned; irrefutable; also sheathed, enclosed in a protective covering of steel"],
		["tit for tat","equivalent retribution; an act of returning exactly what one gets; an eye for an eye, blow for blow"],
		["cornucopia","a symbol of plenty consisting of a goat's horn overflowing with flowers, fruit, and corn"],
		["cubicle","a squared workspace area, usually in offices, one per employee"],
		["accolades","awards or privileges granted as a special honour or as acknowledgement of merit"],
		["adamant","impossible to persuade, or unwilling to change an opinion or decision"],
		["amniocentesis","a medical test in which a needle is used to remove a small amount of the liquid that surrounds a baby in the mother's womb in order to examine the baby's condition"],
		["baker's dozen","a group or set of thirteen, a dozen plus one"],
		["wuss","a coward"],
		["ample","more than enough, fully sufficient"],
		["merry-go-round","children's playground apparatus consisting of a platform that revolves about a fixed center"],
		["maroon","leave trapped and alone in an inaccessible place, especially an island / dark reddish brown"],
		["slumber party","a party when a group of children spends the night at another child's house"],
		["godspeed","used to wish someone good luck when they are setting out on a journey"],
		["turtleneck","a sweater that covers the neck"],
		["assuage","to make unpleasant feelings less strong"],
		["chick lit","genre fiction written by women, about women, for women to read"],
		["circuitously","roundabout, in a way that is not straight or direct"],
		["fender bender","a small car accident in which minimal damage is incurred"],
		["onomatopoeia","a word that's supposed to mimic a sound"],
		["quicksand","loose wet ground that yields easily to pressure and sucks in anything resting on or falling into it"],
		["triage","the process of quickly examining patients who are taken to a hospital in order to decide which ones are the most seriously ill and must be treated first"],
		["start a fad","to initiate a style, activity, or interest that is very popular for a short period of time"],
		["shenanigans","a devious trick used especially for an underhand purpose"],
		["actualize","to bring into existence, make real"],
		["baby blues","a period and feeling of depressiveness after giving birth"],
		["blinkered","limited in understanding, considering only a narrow point of view"],
		["callous","without sympathy or feeling for other people"],
		["gullible","innocent or naive (refers to a person who can be easily manipulated or tricked)"],
		["petri dish","a piece of laboratory equipment, a shallow circular dish with a loose-fitting cover, used to culture bacteria or other microorganisms"],
		["snitch","a person who tells on someone"],
		["waver","to temporarily lose strength, determination, or purpose; hesitate, falter, sway"],
		["attaboy","an expression of encouragement, support, or approval toward a boy, man, or male animal"],
		["attagirl","an expression of encouragement, support, or approval toward a girl, woman, or female animal"],
		["breech delivery","a delivery of a baby with bottom appearing first instead of head"],
		["pig's ear","something that has been badly or clumsily done; a botched job"],
		["portmanteau","a word formed by merging the sounds and meanings of two different words"],
		["redneck","a disparaging term for a member of the white rural labouring class, especially in the southern United States; a person regarded as having a provincial, conservative, often bigoted attitude"],
		["audacity","boldness to do or say something that may be controversial or rude"],
		["tittynope","a small quantity of anything left over"],
		["humdrum","boring, monotonous, not exciting"],
		["heebie-jeebies","a state of nervous fear or anxiety, uneasiness, the jitters"],
		["harum-scarum","reckless, irresponsible, disorganized"],
		["eggnog","a drink made of milk or cream, sugar, eggs, and flavourings that are beaten together and mixed with rum or brandy"],
		["lame duck","an elected officeholder continuing in office during the period between failure to win an election and the inauguration of a successor, an officeholder who has chosen not to run for reelection, an ineffective person, a weakling"],
		["curvaceous","having a well-shaped figure or a well-rounded body (especially of a woman)"],
		["recalcitrance","stubborn resistance to or defiance of authority or guidance; resistance to chemical decomposition"],
		["causeway","a raised road, as over wet ground or a body of water"],
		["Shangri-La","a remote or imaginary utopia, after the fictional Tibetan land of eternal youth in a novel by James Hilton"],
		["burner","a mobile phone used for only a short time and then thrown away so that the owner cannot be traced"],
		["skullduggery","an act or instance of deceitful, duplicitous, or dishonorable trickery, dirty work"],
		["skittish","easily scared or startled, timid"],
		["spunk","semen, to ejaculate, British colloquial"],
		["square one","the starting point, initial stage or step"],
		["sanctimonious","making a show of being morally superior to other people"],
		["conspicuous","very noticeable or attracting attention, often in a way that is not wanted"],
		["convoluted","very twisted, complicated"],
		["impeccable","perfect, with no problems or bad parts"],
		["sycophant","someone who praises powerful or rich people in a way that is not sincere, usually in order to get some advantage from them"],
		["Jaffa Cakes","biscuit-sized cakes introduced by McVitie and Price in the UK in 1927 and named after Jaffa oranges. The most common form of Jaffa cakes are circular, 2 ¹⁄₈ inches in diameter and have three layers: a Genoise sponge base, a layer of orange flavoured jam and a coating of chocolate"],
		["gobbledygook","something written in an overly complex, incoherent, or incomprehensible manner, gibberish, nonsense"],
		["received pronunciation","the instantly recognisable accent often described as typically British"],
		["posh","associated with the upper class, stylish, elegant, exclusive, expensive"],
		["nubile","of an age suitable for marriage; marriageable (about a young woman)"],
		["well-trodden path","a route which is used regularly by a large number of people, and therefore looks worn and is easy to see"],
		["turn tail and run","run away or flee, usually in fear"],
		["benefit of the doubt","a concession that a person or statement must be regarded as correct or justified, if the contrary has not been proven."],
		["turn the tide","change the course of something"],
		["make head or tail of","understand someone or something, usually used in the negative to convey the opposite"],
		["by and large","for the most part, generally, mostly, on the whole, usually, originally used in a nautical context, describing the handling of a ship both to the wind and off it"],
		["cut and run","to abandon a position as quickly as possible, hurry away, escape; sail away quickly by cutting the yarns that hold the sails furled"],
		["hit and run","cause an accident, as with a vehicle, and leave without acknowledging responsibility"],
		["spitting distance","a very short space or distance"],
		["go out on a limb","to do or say something that lacks evidence or support, to take a risk, to hazard a guess"],
		["ride shotgun","to ride in the front passenger seat of a vehicle, next to the driver"],
		["prodigal son","someone who returns home from travelling, especially having repented of former extravagant behaviour"],
		["induction programme","an event to educate the new entrants about the environment in a particular institution, and connect them with the people in it"],
		["laboured breathing","abnormal respiration characterized by evidence of increased effort to breathe, including the use of accessory muscles of respiration, stridor, grunting, or nasal flaring"],
		["run of the mill","ordinary and not special or exciting in any way, regular, not notable, same as many others"],
		["monkey see, monkey do","a conventional explanation for mimicry, especially of a foolish action done with no consideration of the consequences"],
		["poorly endowed","having very small genitalia (about a man) or breasts (about a woman)"],
		["well-endowed","having a lot of something, especially money or possessions, also having large sexual organs (about a man) or large breasts (about a woman)"],
		["read the room","to use one's intuition to analyze the general mood of the people in a particular setting and act accordingly"],
		["trials and tribulations","tests of one's patience or endurance, various difficulties"],
		["rebuttal witness","a person called to provide contradictory evidence"],
		["sight for sore eyes","someone or something that you feel very happy to see"],
		["even money","equal sum staked by each bettor, equal odds in a wager"],
		["cease and desist","a document sent to an individual or business to halt purportedly illegal activity and not take it up again later"],
		["middle ground","a position between two opposite opinions in an argument, or between two descriptions"],
		["cautionary tale","a story that gives a warning"],
		["bat an eyelid","to display even a hint of an emotional response, such as consternation, annoyance, sadness, joy"],
		["ebbs and flows","a recurrent or rhythmical pattern of coming and going or decline and regrowth, referring to the tides; highs and lows, ups and downs"],
		["safe and sound","in one piece, especially after being exposed to danger, completely safe and without injury or damage"],
		["quid pro quo","a reciprocal exchange, something that is given to a person in return for something they have done"],
		["sick and tired","thoroughly weary, discouraged, or bored"],
		["be worried sick","to be very concerned or anxious about a person or situation, worried to death"],
		["rough sleeping","staying outdoors at night, without a place to go home to, a British term for homelessness"],
		["palpable tension","a state of mental or emotional strain or anxiety which can be felt, is obvious and easily perceived"],
		["red herring","a fact, idea, or subject that takes people's attention away from the central point being considered"],
		["pull the plug","to do something that prevents an activity from continuing, especially by no longer giving money to support it"],
		["on top of that","additionally, furthermore, in addition to, besides"],
		["Mary Sue","an idealized female character in film or litereature who is exceptionally talented in a number of areas despite not having had the training or experience to realistically acquire such talents"],
		["from top to toe","encompassing one's entire body; from top to bottom; typically refers to how one is dressed and groomed"],
		["formidable adversary","an opponent or enemy who fights determinedly, continuously, and relentlessly, extremely impressive in strength or excellence"],
		["holier-than-thou","exhibiting an attitude of superior virtue; self-righteously pious"],
		["loud and clear","in a way that reduces or avoids confusion or misunderstanding, easily audible and understandable, used to confirm receiving and understanding a message"],
		["quick and dirty","a popular expression for a survey, lab procedure, or test that uses the tools at hand to answer an experimental question in a crude fashion"],
		["fine and dandy","all right, excellent, nice, good, well, a redundant colloquialism nowadays more often used sarcastically in the sense of \"not all right\" or \"bad\""],
		["head over heels","completely, thoroughly enamored of someone, typically a new romantic partner, the phrase is sometimes followed by \"in love\""],
		["spitting image","a precise resemblance, especially in closely related persons"],
		["long story short","an expression indicating that one is skipping extraneous or unnecessary details and getting to the point"],
		["high seas","the open waters of an ocean or a sea beyond the limits of the territorial jurisdiction of a country"],
		["pinky swear","a promise or oath made ceremonially binding by enjoining the little fingers of two individuals"],
		["silver lining","a comforting or hopeful aspect of an otherwise desperate or unhappy situation (esp in the phrase every cloud has a...)"],
		["acquired taste","something that you dislike at first, but that you start to like after you have tried it a few times"],
		["lo and behold","used to present a new scene, situation, or turn of events, often with the suggestion that, though surprising, it could in fact have been predicted"],
		["alive and kicking","well and healthy, continuing to be popular or successful"],
		["anonymous tip","information about something that is offered by an anonymous source"],
		["bread and butter","someone's main source of income / something ordinary /someone's livelihood"],
		["morbidly obese","overweight in a way that is indicative of disease"],
		["tangible benefits","benefits that can be quantified or measured, especially in money"],
		["vicious cycle","a negative series of events that build on and reinforce each other"],
		["go haywire","to stop working correctly"],
		["guilty as charged","responsible for doing something illegal that you have been accused of in court"],
		["save the day","to do something that prevents a likely defeat or failure"],
		["beyond a shadow of a doubt","with absolute certainty, for sure"],
		["take a rain check","to refuse an offer or invitation with the hope or promise that it can be postponed to a later date or time"],
		["unwavering support","relentless support from someone you can rely on"],
		["call it a day","to cease the activity for the day"],
		["well-disposed","friendly and sympathetic"],
		["unchartered territory","an area not yet explored"],
		["have perfect pitch","to be able to identify a tone without any reference, out of any tonal context"],
		["tickle one's fancy","to be appealing or pleasant to someone"],
		["toss a coin","to give something over to chance, especially when two outcomes are equally likely"],
		["roll the dice","to take some risk on the hope or chance of a fortunate outcome, also literally, in gambling"],
		["run rampant","to go unchecked or without control; to be wild or excessive"],
		["significant other","a person's partner in an intimate relationship, without disclosing or presuming anything about marital status, relationship status, gender identity, or sexual orientation"],
		["occupational hazard","a risk accepted as a consequence of a particular job"],
		["take for granted","to never think about something because you believe it will always be available or stay exactly the same"],
		["immaculate conception","the doctrine, in the Roman Catholic Church, that the Virgin Mary was conceived free from original sin"],
		["be all ears","to be waiting eagerly to hear about something"],
		["eligible bachelor","a particularly desirable potential husband, usually due to wealth, social status or other specific personal qualities"]

	],
	[
		["5973840"], //Advanced English C1-C2 (audio) vol. 2
		["hair of the dog","an alcoholic drink, particularly when taken the morning after to cure a hangover"],
		["coitus","sexual intercourse that includes penetration and ejaculation, a term used in biology and zoology"],
		["come to think of it","when one considers the matter, on reflection; a phrase used when one has had a sudden realization while speaking"],
		["cuckold","a man married to an unfaithful wife, especially when he is unaware or unaccepting of the fact"],
		["cut corners","to skip certain steps in order to do something as easily or cheaply as possible"],
		["cut to the bone","reduced to the lowest possible amount"],
		["cut to the pith","to focus directly on the essential"],
		["cutthroat","fierce, relentless, ruthless, merciless, showing no care or consideration for the harm done to others with whom you are in competition"],
		["dabbler","an amateur who engages in an activity without serious intentions and who pretends to have knowledge, dilettante"],
		["dad dancing","making of embarrassing flamboyant dance moves to pop music by middle-aged men"],
		["Debbie Downer","someone who is constantly making others feel bad or dampening the mood of a group with negative comments"],
		["ditto","as said before; a copy or an imitation; a duplicate of a document; a pokémon that is capable of transforming itself into anything perfectly"],
		["doofus","a slow-witted, incompetent or stupid person, US informal"],
		["Easter egg","a hidden message or feature, as in a video game or DVD; also refers to a traditional religious holiday decoration"],
		["ebony and ivory","two seemingly different things coexisting in harmony that only together create a coherent whole, black and white"],
		["eerie","inspiring inexplicable fear, dread, or uneasiness; strange and frightening; esp. about places and atmosphere"],
		["erstwhile","former, previous; formerly, previously, in the past (formal, archaic)"],
		["expunge","to delete or erase, wipe out, obliterate"],
		["fair and square","honestly, without cheating, following the rules"],
		["fellatio","a method of oral sex where the penis or testicles are stimulated by the partner's mouth"],
		["flip out","to become extremely angry or to lose control of yourself from surprise or shock"],
		["Humpty Dumpty","a short and fat person or a thing that once overthrown or broken cannot be restored or mended; after a nursery rhyme"],
		["mediocre","average, ordinary, undistinguished, barely acceptable but not good enough"],
		["muff diver","one who performs cunnilingus, carpet muncher"],
		["oh boy","a sarcastic expression of delight or joy, surprise, but also dismay, resignation, frustration, or annoyance"],
		["scoop somebody up","to pick somebody up; to lift someone quickly in your arms"],
		["scumbro","a men's fashion style which involves wearing expensive, designer clothing sloppily or cultivating an unfashionable, poorly put together look"],
		["sea legs","the ability to walk steadily on a moving ship; one's comfort level or familiarity with something"],
		["second to none","the very best, better than all the others"],
		["skid row","a district of a city marked by poverty and inferior living conditions, often frequented by vagrants, alcoholics and addicts"],
		["slam dunk","a task so easy that success in it is deemed a certainty; a scoring shot in which a player jumps up and forces the ball down through the basket"],
		["sob one's heart out","to cry loudly for an extended period of time, usually cause of deep sorrow"],
		["stay put","remain somewhere without moving or being moved, in a fixed or established position"],
		["stonks","a term to express a financial decision that resulted in financial gain, mostly used ironically"],
		["sunk into a funk","in a constant long-lasting hopeless decrease of happiness"],
		["switchgrass","a tall North American praire plant used for forage and as a soil stabilizer, being developed as a renewable source of energy"],
		["take a draw","to breathe in smoke from a cigarette into your lungs"],
		["take a stab at","to make an attempt and try something difficult, hard"],
		["take five","take a short break"],
		["tinkerer","someone who likes to experiment with and repair machine parts; historically a traveling mender of metal household utensils"],
		["cover for somebody","to prevent someone from getting into trouble by providing an excuse for them; to do something in place of someone else"],
		["out on a limb","in a position that lacks evidence, certainty or support"],
		["touch-and-go","very uncertain as to the outcome of something, critical"],
		["vestigial tail","something that's present but has no purpose; a rare congenital abnormality, a remnant of a structure found in embryonic life or in ancestral forms"],
		["ahead of the curve","at the forefront of or leading in something, such as a developing situation, field of study or business, social development, etc"],
		["anchor baby","a child born in a country that gives all children born there the right of citizenship, but whose parents are not citizens and do not have the right to live there"],
		["barf","to vomit, to puke; the matter ejected in vomiting"],
		["batten down the hatches","to prepare for a challenging situation"],
		["flaccid","lacking firmness; hanging limply"],
		["goatee","a small chin beard that doesn't cover the chick area, especially one connected to a mustache or trimmed into a point"],
		["be on pins and needles","to be extremely nervous or uneasy, waiting for what is going to happen; in suspense"],
		["bleed six colours","be a fan of Apple Inc."],
		["Big Apple","a nickname for New York City"],
		["cootie","slang name for a head or body louse"],
		["cougar","a mature woman pursuing a younger man for a romantic relationship or a sexual encounter; a puma"],
		["cherry on top","an unnecessary, but welcome, addition to a desirable object or outcome; an allusion to cakes"],
		["throw the baby out with the bathwater","to accidently remove something good in the bid of getting rid of something bad"],
		["pull the trigger","to make a final decision or commit to a certain course of action"],
		["Hail Mary","a traditional catholic prayer to the mother of Jesus"],
		["dead in the water","without any chance for success"],
		["zimmer frame","a walking aid with two wheels in the front, a walker"],
		["barter transaction","the exchange of goods or services in exchange for other goods or services without using a medium of exchange, such as money"],
		["morning after pill","a high-dose oestrogen medication given in the early post-ovulatory period to prevent implantation of a potentially fertilised egg after unprotected intercourse"],
		["traipse around","spend time walking or traveling around in an aimless or carefree search of pleasure"],
		["Lord's Prayer","another name for Our Father or Pater Noster"],
		["tortious interference","a common law tort allowing a claim for damages against a defendant who wrongfully interferes with the plaintiff's contractual or business relationships"],
		["throw a spanner into the works","prevent something from happening smoothly in the way that it was planned by causing a problem or difficulty, maliciously prevent a plan or activity from succeeding"],
		["tenacity","persistant determination, hanging on to something persistantly or stubbornly, relentlessness"],
		["scapegoat","a person or group that is made to carry the blame for others"],
		["spatula","a broad, flat, flexible blade used to mix, spread and lift material including foods, drugs, plaster and paints, in the kitchen it might be used for example to flip burgers"],
		["cross the line","to misbehave or do something unacceptable or inappropriate, go too far"],
		["grim reaper","representation of death as a skeleton in a hooded robe and with a scythe"],
		["have a bee in the bonnet","to keep talking about something again and again because you think it is very important"],
		["behind the curve","not keeping up with current thinking or trends"],
		["bad penny","a person or thing which is unpleasant, disreputable, or otherwise unwanted, especially one which repeatedly appears at inopportune times"],
		["toe-to-toe","(of two people) standing directly in front of one another, especially in order to fight or argue"],
		["bukkake","a sex act in which one participant (or more) is ejaculated on another participant"],
		["taciturn","habitually silent or quiet, inclined to talk very little"],
		["bifurcate","to separate into two parts or branches"],
		["blessing in disguise","a seeming misfortune that turns out to be for the best"],
		["clandestine","kept or done in secret, often to conceal an illicit or improper purpose"],
		["keep at bay","to keep someone or something at a distance or from reaching full potency, especially in order to prevent harm to oneself"],
		["swing for the fences","to put forward one's maximum amount of effort or energy (into or toward something), an expression related to baseball)"],
		["sideburns","facial hair grown at the sides of the face, in front of the ears"],
		["shotgun wedding","a marriage where one or both partners are coerced, usually because the woman is pregnant"],
		["on the edge","close to the point at which something different, usually something bad, will happen"],
		["jump the gun","to do or say something too soon, especially without thinking carefully about it"],
		["excruciating pain","extreme suffering, hard to bear"],
		["effusive","emotionally excessive; overly demonstrative"],
		["drop the ball","to fail in one's responsibilities or duties, or to make a mistake, especially at a critical point or when the result is very negative"],
		["drink the Kool-Aid","to become a firm believer in something without any evidence of veracity; to follow a philosophy blindly"],
		["dead-on","precisely accurate and to the point, exactly right"],
		["dandruff","scaly white dead skin flakes from the human scalp"],
		["debauchery","excessive indulgence in sensual pleasure, sex, alcohol, or drugs"],
		["humblebrag","to make a seemingly modest, self-critical, or casual statement or reference that is meant to draw attention to one's admirable or impressive qualities or achievements"],
		["bait-and-switch","a sales technique, in which an inexpensive product is advertised to prospective customers who are then told the product is unavailable and are instead urged to buy a more expensive product"],
		["bippity boppity boo","a fictitious incantation used by magical people in fiction"],
		["cessation","the fact or process of ending or being brought to an end"],
		["cessation of arms","an agreement of warring parties to stop fighting"],
		["clear as a bell","easy to understand; very clear"],
		["close shave","a narrow escape from serious danger or trouble"],
		["spur of the moment","used to describe a decision that was made quickly and unexpectedly, without thinking, on impulse"],
		["speed bump","a small raised obstacle on the road forcing people to drive more slowly"],
		["soul patch","a single small patch of facial hair just below the lower lip and above the chin"],
		["smoking gun","a piece of incontrovertible incriminating evidence"],
		["shipshape","neat and with everything in its correct place"],
		["shill","an accomplice of a confidence trickster or swindler who poses as a genuine customer to entice or encourage others"],
		["cockamamie","ridiculous, nonsensical, silly"],
		["comeuppance","fate, punishment or retribution that one deserves"],
		["Jane Doe","a name given to an unidentified female who may be party to legal proceedings, or to an unidentified woman in hospital, or dead"],
		["John Doe","a name given to an unidentified man or boy who may be party to legal proceedings, or to an unidentified man in hospital, or dead"],
		["Craigslist","an American classified advertisements website with plenty of sections"],
		["eeny meeny miny moe","a rhyme used by children for choosing between two or more people or things"],
		["same diff","whatever; it's the same"],
		["scot-free","without receiving the deserved or expected punishment or without being harmed"],
		["sabbatical leave","a period of paid leave of absence granted to university staff, teachers, intended to develop and rejuvenate an individual employee, approximately every seventh year"],
		["melee","a noisy, confused fight, a tumultous mingling"],
		["hiatus","a break or a gap or interruption in space, time, or continuity"],
		["gobbledegook","unclear, wordy jargon; specialized language of a group incomprehensible to an outsider, a meaningless jumble of words; imitative of the sound made by a turkey"],
		["ghostwrite","to write something for someone else who is the named author"],
		["what's your poison","used to ask somebody what alcoholic drink they would like, spoken, humorous"],
		["figment of imagination","an experience that initially is thought to be real but is actually not"]
	]
]
